### ISSUE TITLE
Running this on Mac Big Sur in VSC, v 0.5 returns this error. v 0.4 does not.

### ISSUE THREAD

**Issue by Pathos315** [MicheleCotrufo/pdf2doi#5]
Traceback (most recent call last):
  File "/Users/johnfallot/venv/210706_PDN_ScienceAssistant_v16.py", line 3, in <module>
    from pdf2doi.finders import validate
  File "/usr/local/lib/python3.9/site-packages/pdf2doi/__init__.py", line 13, in <module>
    from .main import pdf2doi
  File "/usr/local/lib/python3.9/site-packages/pdf2doi/main.py", line 6, in <module>
    import pdf2doi.utils_registry as utils_registry
  File "/usr/local/lib/python3.9/site-packages/pdf2doi/utils_registry.py", line 5, in <module>
    import winreg 
ModuleNotFoundError: No module named 'winreg'

**Comment by MicheleCotrufo** [comment]
Thank you for posting this. 
This is due to the fact that `pdf2doi` tries to include the module `winreg` which exists only in Windows. This module is only needed for "advanced" functionalities (e.g. being able to call pdf2doi by just right-clicking on a pdf file), but it gets mistakenly loaded at very beginning of one of the main modules. I will fix this in the next version which will be released in a few days.

**Comment by MicheleCotrufo** [comment]
This was solved in version 0.6.
